allowed_commands:
    - status
    - slot1
    - slot2
    - slot3
    - slot4
    - say

toggle_commands:
    - left
    - right
    - forward
    - back
    - jump
    - duck
    - attack
    - attack2

# set this to false on windows
only_run_when_focused: true

# what windows need to be focused to run?
allowed_windows:
    - '*Team Fortress 2*'
    - '*GL*'
